services:
  admin:
    container_name: ticker-admin
    restart: unless-stopped
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    env_file:
      - .env
